server:
#  port: 80
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/endgame.jks
    key-store-password: Aa12345678
    key-alias: endgame
    enabled: true
    
spring:
  devtools:
    restart:
      enabled: true
  flyway:
    enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/endgame?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    password: springstudent
    username: springstudent
  jpa:
    show-sql: false
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          delimiter: ;
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql

#logging:
#  level:
#    web: debug